Repository andela/codepirates-ah-backend, pull requests merged in 2019-08, with the labels that each got.

#5 #167313389 Integrated HoundCi
  .hound.yml
  README.md
Labels: need review

#9 #167701336 failed travis ci build due to bug in app.js file
  lcov.info
  package.json
  src/routes/index.js
Labels: need review

#15 bg(heroku) rename Procfile file
  app.json
  package.json
  src/config/config.js
Labels: need review

#16 Add coverage script
  .coveralls.yml
  package-lock.json
  package.json
Labels: Ready to merge

#14 Ft api social login 167313401
  .env.sample
  package-lock.json
  package.json
  src/app.js
  src/config/oauth.js
  src/controllers/social.js
  src/controllers/user.controller.js
  src/middlewares/passport.js
  src/middlewares/validators/socialLogin-mock.js
  src/mock-data.js
  src/routes/api/index.route.js
  src/routes/api/oauth/docs.js
  src/routes/api/oauth/oauth.routes.js
  src/routes/index.js
  src/seeders/20190805144119-admin.js
  test/test-index.js
  test/test-mock-social.js
  test/test-setup.js
  test/users.test.js
Labels: Ready to merge

#22 #167313402 user profile CRUD operation
  .gitignore
  package-lock.json
  package.json
  src/controllers/profile.controller.js
  src/middlewares/validators/user.profile.validator.js
  src/migrations/20190805142252-create-user.js
  src/models/user.js
  src/routes/api/index.route.js
  src/routes/api/profile/profile.route.js
  src/routes/api/user/user.route.js
  src/services/user.service.js
  test/user.profile.test.js
Labels: need review

#24 #167313413: View profiles of all users.
  package-lock.json
  src/controllers/profile.controller.js
  src/routes/api/profile/profile.route.js
  test/user.profile.test.js
Labels: Ready to be merged

#26 #167313407 Build out commenting on articles REST endpoints(CRUD)
  package-lock.json
  package.json
  src/controllers/comments.controller.js
  src/middlewares/validators/comments.body.js
  src/migrations/20190816101310-create-comment.js
  src/models/comment.js
  src/models/index.js
  src/routes/api/article/article.routes.js
  src/routes/api/comment/comments.route.js
  src/routes/api/index.route.js
  src/services/comments.service.js
Labels: Ready to be merged

#29 Ft like dislike article 167313408
  src/app.js
  src/controllers/likes.controller.js
  src/controllers/profile.controller.js
  src/middlewares/auth.js
  src/middlewares/likes.middleware.js
  src/migrations/20190816132215-create-likes.js
  src/models/article.js
  src/models/likes.js
  src/routes/api/index.route.js
  src/routes/api/likes/doc.yml
  src/routes/api/likes/likes.routes.js
  src/routes/index.js
  src/seeders/20190808074800-normal-user.js
  src/services/likes.service.js
  test/like.test.js
Labels: need review

#30 #167313415 Users should be able to see time it takes to read an article functionality
  package.json
  src/controllers/articles.controller.js
  src/helpers/helper.js
  src/routes/api/article/doc.yml
  src/seeders/20190814094408-demo-article.js
  src/seeders/20190820133339-demo-article-2.js
  test/helper.test.js
  test/test.articles.js
Labels: Ready to be merged

#34 bug(cleanup) clean up test codes
  src/controllers/follow.controller.js
  src/helpers/verification-email.js
  src/services/resetpassword.service.js
  test/like.test.js
  test/test.articles.js
  test/user.profile.test.js
  test/util.test.js
Labels: need review, waiting foranother pr to be merged

#33 #167313412 pagination support for articles
  src/controllers/articles.controller.js
  src/routes/api/article/article.routes.js
  src/routes/api/index.route.js
  src/services/article.service.js
  test/pagination.test.js
Labels: Ready to be merged

#32 #167313414 search functionality
  src/controllers/articles.controller.js
  src/middlewares/query.check.js
  src/routes/api/article/article.routes.js
  src/services/article.service.js
  test/search.test.js
Labels: Ready to be merged

#43 #167313418 report article
  src/controllers/articles.controller.js
  src/controllers/report.comtroller.js
  src/middlewares/likes.middleware.js
  src/middlewares/query.check.js
  src/middlewares/report.middleware.js
  src/middlewares/validators/report.validator.js
  src/migrations/20190823185735-create-reporting.js
  src/models/reporting.js
  src/routes/api/index.route.js
  src/routes/api/reports/doc.yml
  src/routes/api/reports/reports.routes.js
  src/services/report.service.js
  test/reporting.test.js
Labels: Ready to be merged

#47 #167313423 highlight text in the article
  package.json
  src/config/config.js
  src/controllers/highlight.controller.js
  src/helpers/share.article.helper.js
  src/middlewares/shareHighlight.middleware.js
  src/migrations/20190826113358-create-highlight.js
  src/models/article.js
  src/models/highlight.js
  src/models/user.js
  src/routes/api/article/article.routes.js
  src/routes/api/article/doc.yml
  src/services/article.service.js
  test/highlight.test.js
  test/search.test.js
  test/test.articles.js
Labels: Ready to be merged

#45 #167313424 Build out user track comments edit history
  .gitignore
  src/controllers/comments.controller.js
  src/migrations/20190816101310-create-comment.js
  src/models/comment.js
  test/comments.test.js
  test/search.test
Labels: Ready to be merged

#46 #167313416 Users should be able to share articles across different channels
  src/controllers/articles.controller.js
  src/routes/api/article/article.routes.js
  src/routes/api/article/doc.yml
  src/services/notification.service.js
  test/search.test.js
  test/share.article.test.js
Labels: need review

#50 #167313406 refactoring and pagintion for rating article
  src/controllers/rating.controller.js
  src/middlewares/rate.middleware.js
  src/middlewares/validators/rate.validation.js
  src/migrations/20190814093719-create-rate.js
  src/migrations/20190823185735-create-reporting.js
  src/models/rate.js
  src/routes/api/rate/rate.route.js
  src/routes/api/reports/reports.routes.js
  src/services/rate.service.js
  test/rates.test.js
  test/reporting.test.js
Labels: need review
